using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace SourceGenerator;

[Generator]
public class BinarySerializerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes that have the GenerateBinarySerializer attribute
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsClassWithAttribute(node),
                transform: static (ctx, _) => GetClassForGeneration(ctx))
            .Where(static c => c is not null);

        // Combine the classes with the compilation
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        // Register the source generator
        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static bool IsClassWithAttribute(SyntaxNode node)
    {
        // Check if the node is a class declaration
        if (node is not ClassDeclarationSyntax classDeclaration)
            return false;

        // Check if the class has any attributes
        if (classDeclaration.AttributeLists.Count == 0)
            return false;

        // Check if any attribute name matches "GenerateBinarySerializer" or "GenerateBinarySerializerAttribute"
        foreach (var attributeList in classDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var attributeName = attribute.Name.ToString();
                if (attributeName == "GenerateBinarySerializer" || attributeName == "GenerateBinarySerializerAttribute")
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static ClassDeclarationSyntax? GetClassForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        // Get the semantic model
        var semanticModel = context.SemanticModel;

        // Check if the attribute is actually the correct one (not a different type with same name)
        foreach (var attributeList in classDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var attributeSymbol = semanticModel.GetSymbolInfo(attribute).Symbol;
                if (attributeSymbol?.ContainingType?.Name == "GenerateBinarySerializerAttribute")
                {
                    return classDeclaration;
                }
            }
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes, SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty)
            return;

        foreach (var classDecl in classes)
        {
            var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);
            var classSymbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

            if (classSymbol == null)
                continue;

            // Generate source code for this class
            var sourceCode = GeneratePartialClass(classSymbol);
            context.AddSource($"{classSymbol.Name}_BinarySerializer.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }
    }

    private static string GeneratePartialClass(INamedTypeSymbol classSymbol)
    {
        var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;
        var properties = GetPublicProperties(classSymbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Serializes this object to a binary stream using BinaryWriter.");
        sb.AppendLine("    /// Generated by BinarySerializerGenerator.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"stream\">The stream to write to.</param>");
        sb.AppendLine("    public void SerializeToBinary(System.IO.Stream stream)");
        sb.AppendLine("    {");
        sb.AppendLine("        using var writer = new System.IO.BinaryWriter(stream, System.Text.Encoding.UTF8, leaveOpen: true);");
        sb.AppendLine();

        // Generate write statements for each property
        foreach (var property in properties)
        {
            var propertyName = property.Name;
            var propertyType = property.Type;

            if (propertyType.SpecialType == SpecialType.System_Double)
            {
                sb.AppendLine($"        writer.Write(this.{propertyName});");
            }
            else if (propertyType.SpecialType == SpecialType.System_Int32)
            {
                sb.AppendLine($"        writer.Write(this.{propertyName});");
            }
            else if (propertyType.SpecialType == SpecialType.System_String)
            {
                sb.AppendLine($"        writer.Write(this.{propertyName} ?? string.Empty);");
            }
            else if (propertyType.SpecialType == SpecialType.System_DateTime)
            {
                sb.AppendLine($"        writer.Write(this.{propertyName}.ToBinary());");
            }
            else if (propertyType.Name == "ValueTuple`2" && propertyType.ContainingNamespace.Name == "System")
            {
                // Handle tuple properties like (double Longitude, double Latitude)
                sb.AppendLine($"        writer.Write(this.{propertyName}.Item1);");
                sb.AppendLine($"        writer.Write(this.{propertyName}.Item2);");
            }
            else if (propertyType.TypeKind == TypeKind.Struct || propertyType.TypeKind == TypeKind.Class)
            {
                // For custom types, we need to serialize their properties recursively
                // For simplicity in this generator, we'll handle known types like Acceleration
                if (propertyType.Name == "Acceleration")
                {
                    sb.AppendLine($"        writer.Write(this.{propertyName}.Linear);");
                    sb.AppendLine($"        writer.Write(this.{propertyName}.Lateral);");
                    sb.AppendLine($"        writer.Write(this.{propertyName}.Vertical);");
                }
                else
                {
                    sb.AppendLine($"        // Custom type {propertyType.Name} - manual serialization required");
                }
            }
            else
            {
                sb.AppendLine($"        // Type {propertyType} not fully supported - manual serialization required");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("#pragma warning restore");

        return sb.ToString();
    }

    private static ImmutableArray<IPropertySymbol> GetPublicProperties(INamedTypeSymbol classSymbol)
    {
        var properties = new List<IPropertySymbol>();

        // Get all instance properties with public getters and setters
        foreach (var member in classSymbol.GetMembers())
        {
            if (member is IPropertySymbol property &&
                property.DeclaredAccessibility == Accessibility.Public &&
                !property.IsStatic &&
                property.GetMethod != null)
            {
                properties.Add(property);
            }
        }

        return properties.ToImmutableArray();
    }
}